### ISSUE TITLE
Create Donate Page

### ISSUE THREAD

**Issue by mlokc** [codeforkansascity/kc-covid-response#24]
@aarondeacon Can you provide details about the financial integrations? Is it Stripe?

Donate page recommendations are here:
https://docs.google.com/document/d/1nOh_UvRIGxpRTBpbOaqUafr7iiXLxmTO8wAIhFGGzzs/edit?usp=sharing

@RobKraft - Let me know what questions you have.

**Comment by RobKraft** [comment]
We have a donate page now.  Not the one we hoped for, but we will see what feedback we get.
