### ISSUE TITLE
Create Downloads Gallery

### ISSUE THREAD

**Issue by mlokc** [codeforkansascity/kc-covid-response#25]
Here is a rough wireframe for the Downloads Gallery of PDF files. 

https://docs.google.com/presentation/d/1sRaOLUHck6Z0G7bCxOswL3QFlFAlzNR7SKR7nPW29v8/edit?usp=sharing

There needs to be a correspondind admin tool to upload files and categorize them as well.

User should be able to search and browse the library of PDFS
User can select a PDF to download
User sees thumbnails of PDFs
If a PDF has more than one format (Flyer, Document, Poster, etc.), user can select a single format to download or all?

**Comment by RobKraft** [comment]
Duplicate Card
